import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';
import { saveAs } from 'file-saver';
import type { Message } from '@shared/schema';

interface ExportOptions {
  chatTitle: string;
  messages: Message[];
  chartImages?: Map<string, string[]>;
}

function cleanTextForExport(text: string): string {
  let cleaned = text.replace(/```chart[\s\S]*?```/g, '__CHART_BLOCK__');
  cleaned = cleaned.replace(/\[(\d+)\]/g, '[$1]');
  return cleaned;
}

interface TextSegment {
  text: string;
  type: 'h1' | 'h2' | 'h3' | 'normal' | 'bullet' | 'numbered' | 'empty' | 'table' | 'table-placeholder' | 'chart-placeholder';
  indent?: number;
  parts?: Array<{ text: string; bold: boolean }>;
  tableData?: { headers: string[]; rows: string[][] };
}

function parseInlineBold(text: string): Array<{ text: string; bold: boolean }> {
  const parts: Array<{ text: string; bold: boolean }> = [];
  const regex = /(\*\*[^*]+\*\*)/g;
  let lastIndex = 0;
  let match;
  while ((match = regex.exec(text)) !== null) {
    if (match.index > lastIndex) parts.push({ text: text.slice(lastIndex, match.index), bold: false });
    parts.push({ text: match[1].replace(/\*\*/g, ''), bold: true });
    lastIndex = match.index + match[0].length;
  }
  if (lastIndex < text.length) parts.push({ text: text.slice(lastIndex), bold: false });
  return parts.length > 0 ? parts : [{ text, bold: false }];
}

function parsePipeLines(pipeLines: string[]): TextSegment | null {
  const filtered = pipeLines.filter(l => l.trim().startsWith('|'));
  if (filtered.length < 2) return null;

  const headers: string[] = [];
  const rows: string[][] = [];
  let headerParsed = false;

  for (const line of filtered) {
    const cells = line
      .split('|')
      .map(c => c.trim().replace(/\[(?:SQL\d*|SQL)\d*\]/gi, '').trim())
      .filter((_, i, arr) => i > 0 && i < arr.length);

    const isSeparator = cells.every(c => /^:?-+:?$/.test(c));
    if (isSeparator) continue;

    if (!headerParsed) {
      headers.push(...cells);
      headerParsed = true;
    } else {
      rows.push(cells);
    }
  }

  if (headers.length === 0) return null;
  return { text: '', type: 'table', tableData: { headers, rows } };
}

function parseMarkdownForPDF(text: string): TextSegment[] {
  const cleaned = cleanTextForExport(text);
  const lines = cleaned.split('\n');
  const segments: TextSegment[] = [];
  let pipeBuffer: string[] = [];

  function flushPipeBuffer() {
    if (pipeBuffer.length === 0) return;
    const seg = parsePipeLines(pipeBuffer);
    if (seg) segments.push(seg);
    pipeBuffer = [];
  }

  for (const line of lines) {
    if (line.includes('[Full data table attached')) {
      flushPipeBuffer();
      segments.push({ text: '', type: 'table-placeholder' });
      continue;
    }

    if (line.trim() === '__CHART_BLOCK__') {
      flushPipeBuffer();
      segments.push({ text: '', type: 'chart-placeholder' });
      continue;
    }

    if (line.trim().startsWith('|')) {
      pipeBuffer.push(line);
      continue;
    }

    flushPipeBuffer();

    if (line.trim() === '') {
      segments.push({ text: '', type: 'empty' });
      continue;
    }

    if (line.match(/^# /)) {
      segments.push({ text: line.replace(/^# /, ''), type: 'h1' });
    } else if (line.match(/^## /)) {
      segments.push({ text: line.replace(/^## /, ''), type: 'h2' });
    } else if (line.match(/^### /)) {
      segments.push({ text: line.replace(/^### /, ''), type: 'h3' });
    } else if (line.trim().match(/^[-*+]\s/)) {
      const content = line.replace(/^\s*[-*+]\s/, '');
      segments.push({ text: content, type: 'bullet', indent: (line.length - line.trim().length) / 2, parts: parseInlineBold(content) });
    } else if (line.trim().match(/^\d+\.\s/)) {
      const m = line.match(/^(\s*)(\d+)\.\s(.+)$/);
      if (m) {
        const content = `${m[2]}. ${m[3]}`;
        segments.push({ text: content, type: 'numbered', indent: m[1].length / 2, parts: parseInlineBold(content) });
      }
    } else {
      segments.push({ text: line, type: 'normal', parts: parseInlineBold(line) });
    }
  }

  flushPipeBuffer();
  return segments;
}

// ─── PDF EXPORT ──────────────────────────────────────────────────────────────

const FOOTER_LINE1 = 'Generated by LedgerLM AI-powered Intelligence';
const FOOTER_LINE2 =
  'This report was generated using available financial data, source documents, and configured business logic at the time of generation.';

const PAGE_W   = 210;
const PAGE_H   = 297;
const M_LEFT   = 16;
const M_RIGHT  = 16;
const M_TOP    = 18;
const M_BOTTOM = 26; // reserved for footer
const CONTENT_W = PAGE_W - M_LEFT - M_RIGHT;

/** Add the footer to every page once all content has been written. */
function applyFooters(doc: any, totalPages: number) {
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);

    // Separator line
    doc.setDrawColor(180, 180, 180);
    doc.setLineWidth(0.25);
    doc.line(M_LEFT, PAGE_H - 17, PAGE_W - M_RIGHT, PAGE_H - 17);

    // Line 1 – bold label
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(100, 100, 100);
    doc.text(FOOTER_LINE1, M_LEFT, PAGE_H - 13);

    // Line 2 – normal descriptor
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6.5);
    doc.setTextColor(130, 130, 130);
    doc.text(FOOTER_LINE2, M_LEFT, PAGE_H - 9.5);

    // Page number – right-aligned on line 1
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(130, 130, 130);
    doc.text(`Page ${p} of ${totalPages}`, PAGE_W - M_RIGHT, PAGE_H - 13, { align: 'right' });
  }
}

/**
 * Render inline bold/normal parts on a single baseline.
 * Falls back to plain rendering when the text is too wide (no word-wrap support for mixed styles).
 */
function renderInlineParts(
  doc: any,
  parts: Array<{ text: string; bold: boolean }>,
  xStart: number,
  y: number,
  maxWidth: number,
  fontSize: number,
  baseColor: [number, number, number]
) {
  // Measure total width first
  let totalW = 0;
  for (const p of parts) {
    doc.setFont('helvetica', p.bold ? 'bold' : 'normal');
    doc.setFontSize(fontSize);
    totalW += doc.getTextWidth(p.text);
  }

  if (totalW <= maxWidth) {
    // Fits on one line — render with per-part bold
    let cx = xStart;
    for (const p of parts) {
      doc.setFontSize(fontSize);
      doc.setFont('helvetica', p.bold ? 'bold' : 'normal');
      doc.setTextColor(...baseColor);
      doc.text(p.text, cx, y);
      cx += doc.getTextWidth(p.text);
    }
  } else {
    // Too wide — render plain with word-wrap (bold lost, readability preserved)
    const plain = parts.map(p => p.text).join('');
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...baseColor);
    const lines = doc.splitTextToSize(plain, maxWidth);
    doc.text(lines, xStart, y);
  }
}

/** Measure how many mm a segment will consume (approximate). */
function segmentHeight(doc: any, seg: TextSegment): number {
  if (seg.type === 'empty') return 2.5;
  if (seg.type === 'chart-placeholder' || seg.type === 'table-placeholder') return 0;

  if (seg.type === 'table' && seg.tableData) {
    return (seg.tableData.rows.length + 2) * 6 + 4;
  }

  const fontSizeMap: Record<string, number> = { h1: 13, h2: 11, h3: 10, bullet: 9, numbered: 9, normal: 9 };
  const lineHMap:   Record<string, number> = { h1: 6.5, h2: 6, h3: 5.5, bullet: 4.5, numbered: 4.5, normal: 4.5 };
  const fs  = fontSizeMap[seg.type] || 9;
  const lh  = lineHMap[seg.type]   || 4.5;
  const indent = seg.type === 'bullet' || seg.type === 'numbered' ? 6 + (seg.indent || 0) * 3 : 0;

  doc.setFontSize(fs);
  doc.setFont('helvetica', 'normal');
  const lines = doc.splitTextToSize(seg.text || ' ', CONTENT_W - indent);
  return lines.length * lh + 1;
}

export async function exportChatToPDF(options: ExportOptions): Promise<void> {
  const { chatTitle, messages } = options;

  // Dynamic import keeps jspdf out of the initial bundle
  const { jsPDF } = await import('jspdf');

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  let y = M_TOP;

  /** Ensure there is at least `need` mm left; add a new page if not. */
  const guard = (need: number) => {
    if (y + need > PAGE_H - M_BOTTOM) {
      doc.addPage();
      y = M_TOP;
    }
  };

  // ── Cover / title block ───────────────────────────────────────────────────
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(20, 20, 20);
  const titleLines = doc.splitTextToSize(chatTitle, CONTENT_W);
  doc.text(titleLines, M_LEFT, y);
  y += titleLines.length * 7 + 1;

  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(130, 130, 130);
  doc.text(
    `Exported: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`,
    M_LEFT, y
  );
  y += 5;

  doc.setDrawColor(180, 180, 180);
  doc.setLineWidth(0.35);
  doc.line(M_LEFT, y, PAGE_W - M_RIGHT, y);
  y += 6;

  // ── Messages ─────────────────────────────────────────────────────────────
  for (let mi = 0; mi < messages.length; mi++) {
    const message = messages[mi];
    const isUser = message.role === 'user';

    // Sender label
    guard(10);
    const label      = isUser ? 'You' : 'LedgerLM';
    const labelColor: [number, number, number] = isUser ? [0, 90, 180] : [107, 33, 168];
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...labelColor);
    doc.text(label, M_LEFT, y);
    y += 5;

    // Content segments
    const segments = parseMarkdownForPDF(message.content);

    for (const seg of segments) {
      if (seg.type === 'empty') { y += 2.5; continue; }
      if (seg.type === 'chart-placeholder' || seg.type === 'table-placeholder') continue;

      // ── Headings ──────────────────────────────────────────────────────────
      if (seg.type === 'h1') {
        guard(10);
        doc.setFontSize(13);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(25, 25, 25);
        const lines = doc.splitTextToSize(seg.text, CONTENT_W);
        doc.text(lines, M_LEFT, y);
        y += lines.length * 6.5 + 1.5;
        continue;
      }
      if (seg.type === 'h2') {
        guard(9);
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(40, 40, 40);
        const lines = doc.splitTextToSize(seg.text, CONTENT_W);
        doc.text(lines, M_LEFT, y);
        y += lines.length * 6 + 1;
        continue;
      }
      if (seg.type === 'h3') {
        guard(8);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(60, 60, 60);
        const lines = doc.splitTextToSize(seg.text, CONTENT_W);
        doc.text(lines, M_LEFT, y);
        y += lines.length * 5.5 + 0.5;
        continue;
      }

      // ── Bullet ────────────────────────────────────────────────────────────
      if (seg.type === 'bullet') {
        const indent = 5 + (seg.indent || 0) * 3;
        const textW  = CONTENT_W - indent;
        const plain  = seg.parts ? seg.parts.map(p => p.text).join('') : seg.text;
        const lines  = doc.splitTextToSize(plain, textW);
        guard(lines.length * 4.5 + 1);

        doc.setFontSize(9);
        doc.setTextColor(80, 80, 80);
        doc.setFont('helvetica', 'normal');
        doc.text('•', M_LEFT + indent - 4, y);

        if (seg.parts && seg.parts.some(p => p.bold)) {
          renderInlineParts(doc, seg.parts, M_LEFT + indent, y, textW, 9, [80, 80, 80]);
        } else {
          doc.text(lines, M_LEFT + indent, y);
        }
        y += lines.length * 4.5 + 0.5;
        continue;
      }

      // ── Numbered ──────────────────────────────────────────────────────────
      if (seg.type === 'numbered') {
        const indent = 6 + (seg.indent || 0) * 3;
        const textW  = CONTENT_W - indent;
        const plain  = seg.parts ? seg.parts.map(p => p.text).join('') : seg.text;
        const lines  = doc.splitTextToSize(plain, textW);
        guard(lines.length * 4.5 + 1);

        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(80, 80, 80);
        doc.text(lines, M_LEFT + indent, y);
        y += lines.length * 4.5 + 0.5;
        continue;
      }

      // ── Table ─────────────────────────────────────────────────────────────
      if (seg.type === 'table' && seg.tableData) {
        const { headers, rows } = seg.tableData;
        const colCount = Math.max(headers.length, 1);
        const colW     = CONTENT_W / colCount;
        const rowH     = 6;

        guard(rowH + 4);

        // Header background
        doc.setFillColor(237, 233, 254);
        doc.rect(M_LEFT, y - 4.5, CONTENT_W, rowH, 'F');

        doc.setFontSize(8);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(50, 30, 100);
        for (let c = 0; c < headers.length; c++) {
          const cell = doc.splitTextToSize(headers[c], colW - 2);
          doc.text(cell[0] ?? '', M_LEFT + c * colW + 1.5, y);
        }
        y += rowH;

        for (let r = 0; r < rows.length; r++) {
          guard(rowH);
          if (r % 2 === 0) {
            doc.setFillColor(250, 249, 255);
            doc.rect(M_LEFT, y - 4.5, CONTENT_W, rowH, 'F');
          }
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(8);
          doc.setTextColor(55, 55, 55);
          for (let c = 0; c < rows[r].length; c++) {
            const cell = doc.splitTextToSize(rows[r][c] ?? '', colW - 2);
            doc.text(cell[0] ?? '', M_LEFT + c * colW + 1.5, y);
          }
          y += rowH;
        }

        // Outer border
        const tableTopY = y - (rows.length + 1) * rowH;
        doc.setDrawColor(200, 190, 230);
        doc.setLineWidth(0.25);
        doc.rect(M_LEFT, tableTopY - 4.5, CONTENT_W, (rows.length + 1) * rowH + 4.5);

        // Column dividers
        for (let c = 1; c < colCount; c++) {
          doc.line(M_LEFT + c * colW, tableTopY - 4.5, M_LEFT + c * colW, y - rowH + 1.5);
        }

        y += 3;
        continue;
      }

      // ── Normal paragraph ──────────────────────────────────────────────────
      if (seg.text.trim()) {
        const hasBold = seg.parts && seg.parts.some(p => p.bold);
        const plain   = seg.parts ? seg.parts.map(p => p.text).join('') : seg.text;
        const lines   = doc.splitTextToSize(plain, CONTENT_W);
        guard(lines.length * 4.5 + 0.5);

        if (hasBold && seg.parts) {
          renderInlineParts(doc, seg.parts, M_LEFT, y, CONTENT_W, 9, [55, 55, 55]);
        } else {
          doc.setFontSize(9);
          doc.setFont('helvetica', 'normal');
          doc.setTextColor(55, 55, 55);
          doc.text(lines, M_LEFT, y);
        }
        y += lines.length * 4.5 + 0.5;
      }
    }

    // Citations
    const metadata = (message.metadata as { citations?: string[] } | null);
    if (metadata?.citations && metadata.citations.length > 0) {
      y += 2;
      guard(6);
      doc.setFontSize(7.5);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(140, 140, 140);
      doc.text('Sources:', M_LEFT, y);
      y += 3.5;
      for (let i = 0; i < metadata.citations.length; i++) {
        const citText = `[${i + 1}] ${metadata.citations[i]}`;
        const clines  = doc.splitTextToSize(citText, CONTENT_W);
        guard(clines.length * 3.5);
        doc.text(clines, M_LEFT, y);
        y += clines.length * 3.5;
      }
    }

    y += 5;

    // Thin separator between messages
    if (mi < messages.length - 1) {
      guard(4);
      doc.setDrawColor(225, 225, 225);
      doc.setLineWidth(0.2);
      doc.line(M_LEFT, y - 2, PAGE_W - M_RIGHT, y - 2);
    }
  }

  // ── Apply footer to every page ────────────────────────────────────────────
  applyFooters(doc, doc.getNumberOfPages());

  const filename = `${chatTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${Date.now()}.pdf`;
  doc.save(filename);
}

// ─── WORD EXPORT ─────────────────────────────────────────────────────────────

export async function exportChatToWord(options: ExportOptions): Promise<void> {
  const { chatTitle, messages } = options;
  const documentChildren: Paragraph[] = [];

  documentChildren.push(
    new Paragraph({ text: chatTitle, heading: HeadingLevel.HEADING_1, spacing: { after: 200 } })
  );
  documentChildren.push(
    new Paragraph({
      children: [new TextRun({ text: `Exported: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, italics: true, color: '666666', size: 20 })],
      spacing: { after: 400 },
    })
  );

  for (const message of messages) {
    documentChildren.push(
      new Paragraph({
        children: [new TextRun({ text: message.role === 'user' ? 'You' : 'LedgerLM', bold: true, size: 24, color: message.role === 'user' ? '0066CC' : '6B21A8' })],
        spacing: { before: 300, after: 100 },
      })
    );

    const content = cleanTextForExport(message.content);
    const lines = content.split('\n');
    let inList = false;

    for (const line of lines) {
      if (line.trim() === '' || line.trim() === '__CHART_BLOCK__') {
        documentChildren.push(new Paragraph({ text: '' }));
        inList = false;
        continue;
      }
      if (line.startsWith('### ')) {
        documentChildren.push(new Paragraph({ text: line.replace('### ', ''), heading: HeadingLevel.HEADING_3, spacing: { before: 150, after: 100 } }));
        inList = false; continue;
      }
      if (line.startsWith('## ')) {
        documentChildren.push(new Paragraph({ text: line.replace('## ', ''), heading: HeadingLevel.HEADING_2, spacing: { before: 200, after: 100 } }));
        inList = false; continue;
      }
      if (line.startsWith('# ')) {
        documentChildren.push(new Paragraph({ text: line.replace('# ', ''), heading: HeadingLevel.HEADING_1, spacing: { before: 200, after: 100 } }));
        inList = false; continue;
      }
      if (line.trim().match(/^[-*+]\s/)) {
        documentChildren.push(new Paragraph({ text: line.replace(/^\s*[-*+]\s/, ''), bullet: { level: 0 }, spacing: { after: 50 } }));
        inList = true; continue;
      }
      if (line.trim().match(/^\d+\.\s/)) {
        documentChildren.push(new Paragraph({ text: line.replace(/^\s*\d+\.\s/, ''), numbering: { reference: 'default-numbering', level: 0 }, spacing: { after: 50 } }));
        inList = true; continue;
      }
      if (line.trim().startsWith('|')) continue;
      if (line.includes('[Full data table attached')) {
        documentChildren.push(new Paragraph({ children: [new TextRun({ text: '[See full data table in application]', italics: true, color: '666666' })], spacing: { after: 100 } }));
        continue;
      }

      const textRuns: TextRun[] = [];
      const parts = line.split(/(\*\*[^*]+\*\*)/);
      for (const part of parts) {
        if (part.startsWith('**') && part.endsWith('**')) {
          textRuns.push(new TextRun({ text: part.replace(/\*\*/g, ''), bold: true }));
        } else if (part.trim()) {
          textRuns.push(new TextRun({ text: part }));
        }
      }
      if (textRuns.length > 0) {
        documentChildren.push(new Paragraph({ children: textRuns, spacing: { after: inList ? 50 : 100 } }));
      }
      inList = false;
    }

    const metadata = message.metadata as { citations?: string[] } | null;
    if (metadata?.citations && metadata.citations.length > 0) {
      documentChildren.push(new Paragraph({ children: [new TextRun({ text: 'Sources:', italics: true, size: 20, color: '666666' })], spacing: { before: 200, after: 100 } }));
      for (let i = 0; i < metadata.citations.length; i++) {
        documentChildren.push(new Paragraph({ children: [new TextRun({ text: `[${i + 1}] ${metadata.citations[i]}`, size: 18, color: '666666' })], spacing: { after: 50 } }));
      }
    }
    documentChildren.push(new Paragraph({ text: '', spacing: { after: 200 } }));
  }

  const doc = new Document({
    sections: [{ properties: {}, children: documentChildren }],
    numbering: {
      config: [{ reference: 'default-numbering', levels: [{ level: 0, format: 'decimal', text: '%1.', alignment: AlignmentType.LEFT }] }],
    },
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `${chatTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${Date.now()}.docx`);
}
